title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://brgh.github.io/testing-theme

aux_links:
  Template Repository: https://github.com/brgh/testing-theme
